### PR TITLE
New labels & Test methodology

### PR DESCRIPTION
**Pull request by shaded-enmity**

### CODE REVIEW

**Comment by jon-weisz** [comment]
This looks like what we discussed. 
A few questions -  
1 - Should wild cards be allowed? i.e. libati\* libfglrx\* - I think they have to be because the strace call often returns a library that is deeply versioned - i.e. libati.so.2.1.2
2 - The injector will only work if the host is configured correctly. For example, if glxinfo | 'grep direct rendering: ' on the host returns 'direct rendering: No', it will obviously fail in the client. We either want: .test.host, test.client or we want to specify that the test must succeed on both. 
3 - Should any library injectors be allowed a comment? Otherwise, these non-declarative injectors may become quickly opaque to their users. 
4 - Should tests run as part of the install verb unless disabled?

**Comment by shaded-enmity** [comment]
1) I think I should clarify in the docs that I mean that `libati.so` for example will pick up _all versions_ of the given SO-name
2) Yes, that makes sense, I'd make it that both tests have to be passed (`client && host`)
3) Hmm, maybe a comment in the Dockerfile might be sufficient here? Otherwise like with `.test` add another namespace `.comment` or `.description`. This information then could be displayed to the user when in verbose mode for example.
4) I'd make tests opt-in; that is user needs to run the tests explicitly. Ultimately, I'd like to reuse the CLI tool from Atomic (https://github.com/projectatomic/atomic/) which already interprets the standard labels so you'd use Atomic for installing / uninstalling / testing and HICA for running.
HICA is currently configured to run only images already existing on the system for security reasons

**Comment by shaded-enmity** [comment]
The `RUN` label for HICA images could be:

`LABEL RUN="docker-hica --atomic ${IMAGE}"`

The `--atomic` switch would cause HICA to report that it's being run by Atomic, so that if you want to change any of the injector parameters you'll have to run `docker-hica` directly.

**Comment by shaded-enmity** [comment]
Draft edited. WDYT?
@jon-weisz

**Comment by jon-weisz** [comment]
@shaded-enmity That looks good to me. We'll start porting the tacklebox injectors this weekend.

**Pull request merged**
