### PR TITLE
Support for .test and .descriptions labels

### PR DESCRIPTION
**Pull request by shaded-enmity**

### CODE REVIEW

**Comment by jon-weisz** [comment]
This looks great!

**Comment by shaded-enmity** [comment]
I'm thinking how to test the `introspect_runtime` & `library_whitelist` label pair. 
The best idea that I can think of is make these two labels actually part of a single injector, which will need some further changes in how labels are processed, but I'll keep a separate PR for that.

**Comment by shaded-enmity** [comment]
Another idea is to make the `whitelist` part of the `introspect_runtime` label, which makes the most sense at the moment to me:

```
LABEL io.hica.introspect_runtime='glxinfo'
LABEL io.hica.introspect_runtime.whitelist=['libc.so', 'gl.so', 'gfx.so']
```

UPDATE: I've update the label spec to reflect the above change, please review @jon-weisz

**Comment by jon-weisz** [comment]
That looks good.

**Pull request merged**
